import type { MealSlot } from "./training-types";

// Macros: 45+55+35+45 = 180g P · 40+50+30+40 = 160g C · 15+18+7+20 = 60g F → ~1900 cal
export const jonMealSlots: MealSlot[] = [
  {
    key: "meal_1",
    label: "Breakfast",
    time: "7:30 AM",
    targetMacros: { protein: 45, carbs: 40, fat: 15 },
    showVeggies: false,
    options: {
      proteins: [
        { id: "eggs_big", name: "4 whole eggs + 4 whites", serving: "4 + 4", macros: { protein: 44, fat: 20 }, fatHeavy: true },
        { id: "whey_yogurt", name: "1.5 scoops whey + Greek yogurt", serving: "1.5 scoops + 1 cup", macros: { protein: 50, carbs: 8 } },
        { id: "protein_oats", name: "Whey + oats blend", serving: "1.5 scoops + 1/2 cup oats", macros: { protein: 42, carbs: 27, fat: 4 } },
        { id: "eggs_whey", name: "3 whole eggs + 1.5 scoops whey", serving: "3 eggs + whey", macros: { protein: 50, fat: 18 }, fatHeavy: true },
        { id: "greek_yogurt_big", name: "Greek yogurt + whey", serving: "2 cups + 1 scoop", macros: { protein: 58, carbs: 14 } },
        { id: "turkey_sausage", name: "Lean turkey breakfast sausage", serving: "6 oz", macros: { protein: 36, fat: 15 }, fatHeavy: true },
      ],
      carbs: [
        { id: "oats_big", name: "Rolled oats (dry)", serving: "2/3 cup", macros: { carbs: 36 } },
        { id: "oats_berries", name: "Oats + berries", serving: "1/2 cup + 3/4 cup", macros: { carbs: 38 } },
        { id: "oats_banana", name: "Oats + banana", serving: "1/2 cup + 1 medium", macros: { carbs: 40 } },
        { id: "ezekiel_big", name: "Ezekiel bread", serving: "3 slices", macros: { carbs: 45 } },
        { id: "bagel", name: "Whole wheat bagel", serving: "1 medium", macros: { carbs: 48 } },
        { id: "sweet_potato_am", name: "Sweet potato", serving: "1 small (6 oz)", macros: { carbs: 30 } },
      ],
      fats: [
        { id: "auto", name: "Covered by eggs/fatty protein", serving: "none needed", macros: { fat: 0 } },
        { id: "almond_butter_2", name: "Almond butter", serving: "2 tbsp", macros: { fat: 18 } },
        { id: "avocado_third", name: "Avocado", serving: "1/3 fruit", macros: { fat: 10 } },
        { id: "almonds_20", name: "Almonds", serving: "20 nuts", macros: { fat: 14 } },
        { id: "olive_oil_1", name: "Olive oil (for eggs)", serving: "1 tbsp", macros: { fat: 14 } },
      ],
    },
  },
  {
    key: "meal_2",
    label: "Lunch",
    time: "12:30 PM",
    targetMacros: { protein: 55, carbs: 50, fat: 18 },
    showVeggies: true,
    options: {
      proteins: [
        { id: "chicken_breast_big", name: "Chicken breast", serving: "7 oz cooked", macros: { protein: 56 } },
        { id: "turkey_breast_big", name: "Turkey breast", serving: "7 oz cooked", macros: { protein: 56 } },
        { id: "white_fish_big", name: "White fish", serving: "8 oz cooked", macros: { protein: 52 } },
        { id: "shrimp_big", name: "Shrimp", serving: "8 oz cooked", macros: { protein: 56 } },
        { id: "lean_beef_big", name: "93/7 ground beef", serving: "6 oz cooked", macros: { protein: 42, fat: 12 } },
        { id: "tuna_2", name: "Canned tuna", serving: "2 cans", macros: { protein: 60 } },
        { id: "chicken_thigh_big", name: "Chicken thigh", serving: "7 oz cooked", macros: { protein: 45, fat: 18 }, fatHeavy: true },
        { id: "salmon_big", name: "Salmon", serving: "6 oz cooked", macros: { protein: 38, fat: 18 }, fatHeavy: true },
      ],
      carbs: [
        { id: "rice_big", name: "Jasmine rice", serving: "1.25 cups cooked", macros: { carbs: 56 } },
        { id: "basmati_big", name: "Basmati rice", serving: "1.25 cups", macros: { carbs: 56 } },
        { id: "sweet_potato_big", name: "Sweet potato", serving: "1 large (10 oz)", macros: { carbs: 50 } },
        { id: "quinoa_big", name: "Quinoa", serving: "1.25 cups cooked", macros: { carbs: 50 } },
        { id: "potato_big", name: "White potato", serving: "1 large", macros: { carbs: 48 } },
        { id: "pasta_lunch", name: "Pasta (cooked)", serving: "1 cup", macros: { carbs: 45 } },
      ],
      fats: [
        { id: "auto", name: "Covered by fatty protein", serving: "none needed", macros: { fat: 0 } },
        { id: "olive_oil_15", name: "Olive oil", serving: "1.5 tbsp", macros: { fat: 21 } },
        { id: "avocado_half_big", name: "Avocado", serving: "1/2 fruit", macros: { fat: 15 } },
        { id: "almonds_25", name: "Almonds", serving: "25 nuts", macros: { fat: 18 } },
      ],
      veggies: [
        { id: "greens", name: "Mixed greens/spinach", serving: "2-3 cups", macros: {} },
        { id: "broccoli", name: "Broccoli", serving: "2 cups", macros: {} },
        { id: "asparagus", name: "Asparagus", serving: "2 cups", macros: {} },
        { id: "mixed_roasted", name: "Roasted vegetable mix", serving: "2 cups", macros: {} },
        { id: "cauliflower", name: "Cauliflower", serving: "2 cups", macros: {} },
        { id: "peppers", name: "Bell peppers", serving: "2 cups", macros: {} },
      ],
    },
  },
  {
    key: "meal_3",
    label: "Snack",
    time: "3:30 PM",
    targetMacros: { protein: 35, carbs: 30, fat: 7 },
    showVeggies: false,
    options: {
      proteins: [
        { id: "whey_banana_big", name: "Whey + banana", serving: "1.5 scoops + 1 medium", macros: { protein: 37, carbs: 27 } },
        { id: "whey_double", name: "Whey isolate (in water)", serving: "2 scoops", macros: { protein: 50 } },
        { id: "yogurt_berries_big", name: "Greek yogurt + berries", serving: "1.5 cups + 1 cup", macros: { protein: 36, carbs: 20 } },
        { id: "cottage_apple", name: "Cottage cheese + apple", serving: "1.5 cups + 1 medium", macros: { protein: 38, carbs: 28 } },
        { id: "tuna_crackers", name: "Tuna + crackers", serving: "1.5 cans + 6 crackers", macros: { protein: 42, carbs: 22 } },
        { id: "jerky_cheese", name: "Beef jerky + string cheese", serving: "2 oz jerky + 2 sticks", macros: { protein: 36, fat: 10 } },
      ],
      carbs: [
        { id: "auto", name: "Included in protein choice", serving: "covered", macros: { carbs: 0 } },
        { id: "banana_med", name: "Medium banana", serving: "1 medium", macros: { carbs: 27 } },
        { id: "apple_med", name: "Apple", serving: "1 medium", macros: { carbs: 25 } },
        { id: "rice_cakes_4", name: "Rice cakes", serving: "4 cakes", macros: { carbs: 28 } },
      ],
      fats: [
        { id: "none", name: "No added fat", serving: "none", macros: { fat: 0 } },
        { id: "almond_butter_small", name: "Almond butter", serving: "1 tsp", macros: { fat: 3 } },
        { id: "almonds_10", name: "Almonds", serving: "10 nuts", macros: { fat: 7 } },
      ],
    },
  },
  {
    key: "meal_4",
    label: "Dinner",
    time: "7:00 PM",
    targetMacros: { protein: 45, carbs: 40, fat: 20 },
    showVeggies: true,
    options: {
      proteins: [
        { id: "chicken_breast_dinner", name: "Chicken breast", serving: "6 oz cooked", macros: { protein: 48 } },
        { id: "white_fish_dinner", name: "White fish", serving: "7 oz cooked", macros: { protein: 46 } },
        { id: "shrimp_dinner", name: "Shrimp", serving: "7 oz cooked", macros: { protein: 50 } },
        { id: "lean_beef_dinner", name: "93/7 ground beef", serving: "5 oz cooked", macros: { protein: 35, fat: 10 } },
        { id: "pork_tenderloin", name: "Pork tenderloin", serving: "6 oz cooked", macros: { protein: 45, fat: 8 } },
        { id: "ribeye_lean", name: "Lean sirloin/ribeye", serving: "5 oz cooked", macros: { protein: 38, fat: 18 }, fatHeavy: true },
        { id: "salmon_dinner", name: "Salmon", serving: "5 oz cooked", macros: { protein: 32, fat: 15 }, fatHeavy: true },
      ],
      carbs: [
        { id: "sweet_potato_dinner", name: "Sweet potato", serving: "1 medium", macros: { carbs: 38 } },
        { id: "rice_dinner", name: "Jasmine rice", serving: "1 cup cooked", macros: { carbs: 45 } },
        { id: "potato_dinner", name: "White potato", serving: "1 medium", macros: { carbs: 36 } },
        { id: "quinoa_dinner", name: "Quinoa", serving: "1 cup cooked", macros: { carbs: 40 } },
        { id: "pasta_dinner", name: "Pasta (cooked)", serving: "3/4 cup", macros: { carbs: 36 } },
        { id: "no_carb_dinner", name: "Skip starch (extra veggies)", serving: "extra veggies only", macros: { carbs: 0 } },
      ],
      fats: [
        { id: "auto", name: "Covered by fatty protein", serving: "none needed", macros: { fat: 0 } },
        { id: "olive_oil_dinner", name: "Olive oil", serving: "1.5 tbsp", macros: { fat: 21 } },
        { id: "avocado_half_dinner", name: "Avocado", serving: "1/2 fruit", macros: { fat: 15 } },
        { id: "almonds_dinner", name: "Almonds", serving: "25 nuts", macros: { fat: 18 } },
        { id: "butter_oil", name: "Butter + olive oil", serving: "1 tbsp + 1 tsp", macros: { fat: 16 } },
      ],
      veggies: [
        { id: "roasted_mix", name: "Roasted vegetable mix", serving: "2 cups", macros: {} },
        { id: "broccoli", name: "Broccoli", serving: "2 cups", macros: {} },
        { id: "asparagus_zucchini", name: "Asparagus + zucchini", serving: "2 cups", macros: {} },
        { id: "green_beans", name: "Green beans", serving: "2 cups", macros: {} },
        { id: "brussels", name: "Brussels sprouts", serving: "2 cups", macros: {} },
        { id: "cauliflower", name: "Cauliflower (roasted)", serving: "2 cups", macros: {} },
      ],
    },
  },
];
